### ISSUE TITLE
EnvironmentEnjoyer doesnt work?

### ISSUE THREAD

**Issue by Marukao7** [CWXDEV/MegaMod#3]
Is it just me or the EnvironmentEnjoyer addon is not working like it was in 3.9.x? it seem to not remove trees or bushes like 3.9.x was.

**Comment by CWXDEV** [comment]
How so? what map? i tried it on customs and streets and it looked the same. is it missing bushes and tree's?

**Comment by Marukao7** [comment]
its not working on ground zero, im guessing thats a design choice then?

**Comment by CWXDEV** [comment]
Not at all, I should have a bit of time later today to check it out, BSG may have changed somethings.
My fault for not checking every map.

**Comment by CWXDEV** [comment]
Found the bug, BSG partially changed the GameObject names I was searching for. this will be fixed in the next release
