### ISSUE TITLE
fall damage?

### ISSUE THREAD

**Issue by Linvasor** [CWXDEV/MegaMod#4]
with the new version of the mod everytime i jump or fall from a very small height my character receives massive leg damage, i tested without the mod and there's no issue

**Comment by CWXDEV** [comment]
im seeing the issue aswell, for some reason when setting it back to the old safe height, its setting it to 0. thanks for the report

**Comment by CWXDEV** [comment]
This should be fixed now, please download the latest version and give it a go please

**Comment by Linvasor** [comment]
it works fine now, thanks

**Comment by CWXDEV** [comment]
perfect, thanks for letting me know
